---
title: "Homework 3"
format: html
editor: visual
---

## Task 1: Control Flow Practice


```{r}
#| echo: false
    setwd("C:/Users/Madelyn Garrison/OneDrive - East Carolina University/Desktop/Homework-3")
    load(file='hw2_list.rda')
```  

First, initialize new variables.
```{r}
    bp_list$treatment$status<-character(20)
    bp_list$placebo$status<-character(10)
```
Use if/then/else to fill new variable for treatment group.
```{r}
    for (i in 1:nrow(bp_list$treatment)){
      if (bp_list$treatment$post_bp[i] <= 120){
       bp_list$treatment$status[i] = "optimal"
      }
        else if (bp_list$treatment$post_bp[i] > 120 & 
             bp_list$treatment$post_bp[i] <= 130) {
      bp_list$treatment$status[i] = "borderline" 
      }
        else if (bp_list$treatment$post_bp[i] > 130){
             bp_list$treatment$status[i] = "high" 
      }
      }
```
Do the same for placebo group.

```{r}
    for (i in 1:nrow(bp_list$placebo)){
      if (bp_list$placebo$post_bp[i] <= 120){
       bp_list$placebo$status[i] = "optimal"
      }
        else if (bp_list$placebo$post_bp[i] > 120 & 
             bp_list$placebo$post_bp[i] <= 130) {
      bp_list$placebo$status[i] = "borderline" 
      }
    else if (bp_list$placebo$post_bp[i] > 130){
      bp_list$placebo$status[i] = "high"
      }
      }
```

## Task 2: Function Writing

The function below takes in a list identical in structure to bp_list and an R function specified by the user, with mean being the default. The same can be done using different summary statistics.

```{r}
summ_function<-function(x, stat='mean'){
      my_func<-get(stat)
      a<-my_func(bp_list$treatment$pre_bp)
      b<-my_func(bp_list$treatment$post_bp)
      c<-my_func(bp_list$treatment$diff_bp)
      d<-my_func(bp_list$placebo$pre_bp)
      e<-my_func(bp_list$placebo$post_bp)
      f<-my_func(bp_list$placebo$diff_bp)
      values<-c(a,b,c,d,e,f)
      names(values)<-c(paste("treatment_pre_bp",stat,sep='_'),
                       paste("treatment_post_bp",stat,sep='_'),
                       paste("treatment_diff_bp",stat,sep='_'),
                       paste("placebo_pre_bp",stat,sep='_'),
                       paste("placebo_post_bp",stat,sep='_'),
                       paste("placebo_diff_bp",stat,sep='_'))
      return(values)
    }
    summ_function(bp_list)
    summ_function(bp_list,'var')
    summ_function(bp_list,'sd')
    summ_function(bp_list,'min')
    summ_function(bp_list,'max')
```
    